name: Example action

on: workflow_dispatch

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - uses: EyevinnOSC/action@main
      with:
        args: create birme-mariadb-backup-s3 example -o MariaDbUrl="{{secrets.oscblogdburl}}" -o awsAccessKeyId="{{secrets.eyevinnawskeyid}}" -o awsSecretAccessKey="{{secrets.eyevinnawssecret}}" -o awsRegion="eu-north-1" -o cmdLineArgs="s3://osaas-backup/blog/"
      env:
        OSC_ACCESS_TOKEN: ${{ secrets.OSC_ACCESS_TOKEN }}
